export const theme = {
  Border: {
    radius: '0.4%',
  },
  Font: {
    family:
      "Poppins, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    light: 300,
    normal: 400,
    bold: 600,
    sizes: {
      xsmall: '1%',
      small: '1.4%',
      medium: '1.6%',
      large: '1.8%',
      xlarge: '2.0%',
      xxlarge: '2.8%',
    },
  },
  Colors: {
    Backgroud: '#1C1A29',
    White: '#FAFAFA',
    ButtonDanger: '#D27A7A',
    BackgourndInput: '#2F2C44',
    secondary: '#2f2c441d',
    mainBg: '#0e0d2e',
    black: '#030517',
    lightGray: '#e4e4e4',
    gray: '#8F8F8F',
    darkGray: '#2E2F42',
    border: '#2e9aff',
    buttonDefault: '#867AD2',
    buttonConfirm: '#7AD27D',
    warning: '#e7eb12',
    text: '#c5c5c5',
  },
  Spacings: {
    xxsmall: '0.5%',
    xsmall: '1.6%',
    small: '2.4%',
    medium: '3.2%',
    large: '4.0%',
    xlarge: '4.8%',
    xxlarge: '5.6%',
  },
  Layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
  Sizes: {
    small: '5%',
    medium: '10%',
    large: '20%',
    fullWidth: '100%',
  },
};
